/*
.


Diccionarios
Validar formularios
colores
manejar tipos de errores
show/hide password

 "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViODc4ODBiNzQ0NjZhMDAyYzFkYjA1YSIsImVtYWlsIjoiaXZhbnZlZ2EwOEBvdXRsb29rLmNvbSIsImZpcnN0bmFtZSI6Ikl2YW4iLCJsYXN0bmFtZSI6Ik1hcnRpbmV6IiwiaWF0IjoxNTM1NjA5MDcwLCJleHAiOjE1MzY5MDUwNzB9.OE2wHuG3pmziBom4-SbXrq_aiEO07pejqTVbgdn-IKQ"

.*/
